/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Paso1`; params?: Router.UnknownInputParams; } | { pathname: `/Paso2`; params?: Router.UnknownInputParams; } | { pathname: `/Paso3`; params?: Router.UnknownInputParams; } | { pathname: `/Paso4`; params?: Router.UnknownInputParams; } | { pathname: `/Paso5`; params?: Router.UnknownInputParams; } | { pathname: `/Paso6`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/shared`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Paso1`; params?: Router.UnknownOutputParams; } | { pathname: `/Paso2`; params?: Router.UnknownOutputParams; } | { pathname: `/Paso3`; params?: Router.UnknownOutputParams; } | { pathname: `/Paso4`; params?: Router.UnknownOutputParams; } | { pathname: `/Paso5`; params?: Router.UnknownOutputParams; } | { pathname: `/Paso6`; params?: Router.UnknownOutputParams; } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/shared`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Paso1${`?${string}` | `#${string}` | ''}` | `/Paso2${`?${string}` | `#${string}` | ''}` | `/Paso3${`?${string}` | `#${string}` | ''}` | `/Paso4${`?${string}` | `#${string}` | ''}` | `/Paso5${`?${string}` | `#${string}` | ''}` | `/Paso6${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/shared${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Paso1`; params?: Router.UnknownInputParams; } | { pathname: `/Paso2`; params?: Router.UnknownInputParams; } | { pathname: `/Paso3`; params?: Router.UnknownInputParams; } | { pathname: `/Paso4`; params?: Router.UnknownInputParams; } | { pathname: `/Paso5`; params?: Router.UnknownInputParams; } | { pathname: `/Paso6`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/shared`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
