fun main() {
    println("Listas - Clinica Veterinaria")
    println("Inmutables")
    val razas = listOf("Labrador", "Pastor Aleman", "Bulldog", "Poodle", "Chihuahua")
    println(razas)
    println("Size: ${razas.size}")
    println("Mostrar el elemento indice 0: ${razas[0]}")
    println("Mostrar primer elemento: ${razas.first()}")
    println("Mostrar ultimo elemento: ${razas.last()}")

    println("Mostrar el elemento indice 2: ${razas.get(2)}")
    println("Mostrar el contenido segun indice: ${razas.indexOf("Bulldog")}")
    println("Verificar existencia de un elemento: ${razas.contains("Poodle")}")
    println("Verificar existencia de un elemento: ${"Beagle" in razas}")

    println("Sublista: ${razas.subList(1, 4)}")
    println("Tomar primeros 2 elementos: ${razas.take(2)}")
    println("Suprimir tres primeros elemento: ${razas.drop(3)}")
    println("Tomar los ultimos dos elementos: ${razas.takeLast(2)}")
    println(razas)
    print("Mutables")
    val servicios = mutableListOf("Consulta", "Vacunacion", "Peluqueria", "Cirugia")
    println(servicios)
    servicios.add("Hospitalizacion")
    println(servicios)
    servicios.add(1, "Desparasitacion")
    println(servicios)
    servicios.remove("Peluqueria")
    println(servicios)
    servicios[1] = "Esterilizacion"
    println(servicios)

    println("Array deque")
    val historialPeso = ArrayDeque<Double>()
    println(historialPeso)
    historialPeso.addFirst(12.5)
    println(historialPeso)
    historialPeso.addFirst(13.0)
    println(historialPeso)
    historialPeso.addLast(12.8)
    println(historialPeso)
    historialPeso.removeFirst()
    println(historialPeso)
    historialPeso.removeLast()
    println(historialPeso)
}
