fun main() {
    println("Set - Clinica Veterinaria")
    println("Inmutables")
    val especies = setOf("Perro", "Gato", "Ave", "Roedor", "Reptil", "Gato", "Perro", "Ave")
    println(especies)
    println("Operaciones de Conjuntos")
    val domesticos = setOf("Perro", "Gato", "Conejo")
    println("domesticos: $domesticos")
    val exotico = setOf("Ave", "Reptil", "Conejo", "HurOn")
    println("exotico: $exotico")
    println("Union: ${domesticos union exotico}")
    println("Interseccion: ${exotico intersect domesticos}")
    println("Substraccion: ${domesticos subtract exotico}")
    println("domesticos: $domesticos")
    println("exotico: $exotico")

    println("Set Mutables")
    val pacientes = mutableSetOf("Max", "Luna", "Toby")
    println(pacientes)
    pacientes.add("max")
    println(pacientes)
    pacientes.remove("Luna")
    println(pacientes)
    pacientes.remove("Luna")
    println(pacientes)
    println("Verificar el valor existente: ${"Max" in pacientes}")
    println("Verificar el valor existente: ${"Luna" in pacientes}")
}
