fun main() {
    println("Set")
    println("Inmutables")
    val numeros = setOf(1, 2, 3, 4, 6, 5, 3, 4, 2, 1 , 1, 3) 
    println(numeros)
    println("Operaciones de Conjuntos")
    val pares = setOf(2, 4, 6, 8, 10)
    println("pares: $pares")
    val impares = setOf(1, 3, 5, 7, 9)
    val multiplos3 = setOf(3, 6, 9, 12)
    println("impares: $impares")
    println("Unión: ${pares union impares}")
    println("Intersección: ${multiplos3 intersect impares}")
    println("Substracción: ${pares subtract multiplos3}")
    println("pares: $pares")
    println("impares: $impares")

    println("Set")
    println("Mutables")
    val lenguajes = mutableSetOf("Kotlin", "Java", "Reactnative")
    println(lenguajes)
    lenguajes.add("kotlin")
    println(lenguajes)
    lenguajes.remove("javascript")
    println(lenguajes)
    lenguajes.remove("Java")
    println(lenguajes)
    println("Verificar el valor existente: ${"Kotlin" in lenguajes}")
    println("Verificar el valor existente: ${"Java" in lenguajes}")
}